usecase-beta
actor Administrateur
actor auteur
actor visiteur
system["blog"]

Administrateur -- GERER LE CONTENU -- system
auteur -- Rédige et gère ses articles -- system
visiteur -- Consulte les articles publiés -- system
