usecase-beta
actor Administrateur
actor auteur
actor visiteur

blog

Administrateur -- GERER LE CONTENU -- blog
auteur -- Rédige et gère ses articles -- blog
visiteur -- Consulte les articles publiés -- blog
